import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          RegisterGroup(),
        ]),
      ),
    );
  }
}

class RegisterGroup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 341,
          height: 68,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 341,
                  height: 68,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF020000)),
                      borderRadius: BorderRadius.circular(9),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 120,
                top: 18,
                child: SizedBox(
                  width: 98,
                  height: 27,
                  child: SizedBox(
                    width: 98,
                    height: 27,
                    child: Text(
                      'register',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 24,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w400,
                        height: 1.21,
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 341,
          height: 372,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 68,
                child: Container(
                  width: 341,
                  height: 304,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF261C1C)),
                      borderRadius: BorderRadius.circular(9),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 165,
                child: Container(
                  width: 227,
                  height: 162,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 122,
                        child: Container(
                          width: 89,
                          height: 40,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(9)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 25,
                        top: 135,
                        child: SizedBox(
                          width: 38,
                          height: 17,
                          child: SizedBox(
                            width: 38,
                            height: 17,
                            child: Text(
                              'sign up',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 10,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 227,
                          height: 40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 227,
                                  height: 40,
                                  decoration:
                                      BoxDecoration(color: Color(0x4CE0E0E0)),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 11,
                                child: SizedBox(
                                  width: 174,
                                  height: 17,
                                  child: SizedBox(
                                    width: 174,
                                    height: 17,
                                    child: Text(
                                      'input ID',
                                      style: TextStyle(
                                        color: Colors.black
                                            .withOpacity(0.15000000596046448),
                                        fontSize: 14,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 1.21,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 65,
                        child: Container(
                          width: 227,
                          height: 40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 227,
                                  height: 40,
                                  decoration:
                                      BoxDecoration(color: Color(0x4CE0E0E0)),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 10,
                                child: SizedBox(
                                  width: 174,
                                  height: 17,
                                  child: SizedBox(
                                    width: 174,
                                    height: 17,
                                    child: Text(
                                      'input Password',
                                      style: TextStyle(
                                        color: Colors.black
                                            .withOpacity(0.15000000596046448),
                                        fontSize: 14,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 1.21,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 166,
                top: 287,
                child: Container(
                  width: 118,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 118,
                          height: 40,
                          decoration: BoxDecoration(color: Color(0x00D9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 12,
                        child: SizedBox(
                          width: 87,
                          height: 15,
                          child: SizedBox(
                            width: 87,
                            height: 15,
                            child: Text(
                              '𝙛𝙤𝙧𝙜𝙤𝙩 𝙥𝙖𝙨𝙨𝙤𝙬𝙧𝙙?',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 10,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 65,
                top: 0,
                child: Container(
                  width: 211,
                  height: 145,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/211x145"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
