import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          BigMapGroup(),
        ]),
      ),
    );
  }
}

class BigMapGroup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 280,
          height: 460,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 280,
                  height: 402.25,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/280x402"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 399.90,
                child: Container(
                  width: 280,
                  height: 60.11,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 60.11,
                          decoration: BoxDecoration(
                            color: Colors.white,
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x660C0C0D),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: -8,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35.47,
                        top: 10.54,
                        child: Container(
                          width: 27.53,
                          height: 47.53,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0.53,
                                top: 23.22,
                                child: SizedBox(
                                  width: 27,
                                  height: 24.32,
                                  child: SizedBox(
                                    width: 27,
                                    height: 24.32,
                                    child: Text(
                                      'map',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 219.33,
                        top: 9.49,
                        child: Container(
                          width: 51.85,
                          height: 45.34,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 24.25,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 21.09,
                                  child: SizedBox(
                                    width: 51.85,
                                    height: 21.09,
                                    child: Text(
                                      'profile',
                                      style: TextStyle(
                                        color: Color(0xFFC2C2C2),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 128.80,
                        top: 10.54,
                        child: Container(
                          width: 51.89,
                          height: 44.29,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0.03,
                                top: 23.20,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 21.09,
                                  child: SizedBox(
                                    width: 51.85,
                                    height: 21.09,
                                    child: Text(
                                      'chat',
                                      style: TextStyle(
                                        color: Color(0xFFC2C2C2),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 19.25,
                child: Container(
                  width: 260,
                  height: 28.37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 260,
                          height: 28.37,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 7.09,
                        child: SizedBox(
                          width: 147,
                          height: 18.24,
                          child: SizedBox(
                            width: 147,
                            height: 18.24,
                            child: Text(
                              '검색',
                              style: TextStyle(
                                color: Color(0xFFC2C2C2),
                                fontSize: 11,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
