import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          BigMapGroup(),
        ]),
      ),
    );
  }
}

class BigMapGroup extends StatelessWidget {
  const BigMapGroup({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          width: 280,
          height: 460,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 280,
                  height: 402.25,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/280x402"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 399.90,
                child: SizedBox(
                  width: 280,
                  height: 60.11,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 60.11,
                          decoration: BoxDecoration(
                            color: Colors.white,
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x660C0C0D),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: -8,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35.47,
                        top: 10.54,
                        child: SizedBox(
                          width: 27.53,
                          height: 47.53,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0.53,
                                top: 23.22,
                                child: SizedBox(
                                  width: 27,
                                  height: 24.32,
                                  child: SizedBox(
                                    width: 27,
                                    height: 24.32,
                                    child: Text(
                                      'map',
                                      style: TextStyle(
                                        color: Color(0xFFC2C2C2),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 219.33,
                        top: 9.49,
                        child: SizedBox(
                          width: 51.85,
                          height: 45.34,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 24.25,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 21.09,
                                  child: ElevatedButton(
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) => BigMyGroup()),
                                      );
                                    },
                                    child: Text(
                                      'map',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 128.80,
                        top: 10.54,
                        child: SizedBox(
                          width: 51.89,
                          height: 44.29,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0.03,
                                top: 23.20,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 21.09,
                                  child: ElevatedButton(
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                BigChatGroup()),
                                      );
                                    },
                                    child: Text(
                                      'chat',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 19.25,
                child: SizedBox(
                  width: 260,
                  height: 28.37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 260,
                          height: 28.37,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 7.09,
                        child: SizedBox(
                          width: 147,
                          height: 18.24,
                          child: SizedBox(
                            width: 147,
                            height: 18.24,
                            child: Text(
                              '검색',
                              style: TextStyle(
                                color: Color(0xFFC2C2C2),
                                fontSize: 11,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class BigChatGroup extends StatelessWidget {
  const BigChatGroup({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          width: 280,
          height: 461,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 280,
                  height: 459.95,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 402.46,
                child: Container(
                  width: 280,
                  height: 57.49,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(9)),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: SizedBox(
                  width: 280,
                  height: 402.46,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 402.46,
                          decoration: BoxDecoration(
                            color: Color(0xFFFCFCFC),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x660C0C0D),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: -8,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17.73,
                        top: 268.65,
                        child: SizedBox(
                          width: 244.53,
                          height: 101.40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 244.53,
                                  height: 99.31,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                          width: 1, color: Color(0xFFC2C2C2)),
                                      borderRadius: BorderRadius.circular(9),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 31.73,
                                top: 9.41,
                                child: SizedBox(
                                  width: 189.47,
                                  height: 13.59,
                                  child: SizedBox(
                                    width: 189.47,
                                    height: 13.59,
                                    child: Text(
                                      '인기 게시판',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 11.20,
                                top: 26.13,
                                child: SizedBox(
                                  width: 159.60,
                                  height: 75.27,
                                  child: SizedBox(
                                    width: 159.60,
                                    height: 75.27,
                                    child: Text(
                                      '~~~~~~~~~\n************\n%%%%%%%%%\n@@@@@@@',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17.73,
                        top: 19.86,
                        child: SizedBox(
                          width: 244.53,
                          height: 101.40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 244.53,
                                  height: 99.31,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                          width: 1, color: Color(0xFFC2C2C2)),
                                      borderRadius: BorderRadius.circular(9),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9.33,
                                top: 26.13,
                                child: SizedBox(
                                  width: 159.60,
                                  height: 75.27,
                                  child: SizedBox(
                                    width: 159.60,
                                    height: 75.27,
                                    child: Text(
                                      '~~~~~~~~~\n************\n%%%%%%%%%\n@@@@@@@',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28.93,
                                top: 9.41,
                                child: SizedBox(
                                  width: 145.60,
                                  height: 90.95,
                                  child: SizedBox(
                                    width: 145.60,
                                    height: 90.95,
                                    child: Text(
                                      '내가 고정한 게시글 & 게시판',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17.73,
                        top: 144.26,
                        child: SizedBox(
                          width: 244.53,
                          height: 99.31,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 244.53,
                                  height: 99.31,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                          width: 1, color: Color(0xFFC2C2C2)),
                                      borderRadius: BorderRadius.circular(9),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 9.33,
                                top: 26.13,
                                child: SizedBox(
                                  width: 159.60,
                                  height: 54.36,
                                  child: SizedBox(
                                    width: 159.60,
                                    height: 54.36,
                                    child: Text(
                                      '~~~~~~~~~\n************\n%%%%%%%%%\n@@@@@@@',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 28.93,
                                top: 9.41,
                                child: SizedBox(
                                  width: 144.67,
                                  height: 28.22,
                                  child: SizedBox(
                                    width: 144.67,
                                    height: 28.22,
                                    child: Text(
                                      '내가 자주가는 게시판',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 401.42,
                child: SizedBox(
                  width: 280,
                  height: 59.58,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 59.58,
                          decoration: BoxDecoration(
                            color: Colors.white,
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x660C0C0D),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: -8,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 10.45,
                        child: SizedBox(
                          width: 28,
                          height: 44.12,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 22.07,
                                child: SizedBox(
                                  width: 28,
                                  height: 22.05,
                                  child: ElevatedButton(
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                BigMapGroup()),
                                      );
                                    },
                                    child: Text(
                                      'map',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 219.33,
                        top: 9.41,
                        child: SizedBox(
                          width: 51.85,
                          height: 44.95,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 24.04,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 20.91,
                                  child: ElevatedButton(
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) => BigMyGroup()),
                                      );
                                    },
                                    child: Text(
                                      'Profile',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 128.80,
                        top: 10.45,
                        child: SizedBox(
                          width: 51.89,
                          height: 43.90,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0.03,
                                top: 23,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 20.91,
                                  child: SizedBox(
                                    width: 51.85,
                                    height: 20.91,
                                    child: Text(
                                      'chat',
                                      style: TextStyle(
                                        color: Color(0xFF0F0F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class BigMyGroup extends StatelessWidget {
  const BigMyGroup({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          width: 280,
          height: 460,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 280,
                  height: 460,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 20,
                top: 20,
                child: SizedBox(
                  width: 240,
                  height: 130,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 240,
                          height: 130,
                          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                        ),
                      ),
                      Positioned(
                        left: 18,
                        top: 31,
                        child: Container(
                          width: 68,
                          height: 68,
                          decoration: ShapeDecoration(
                            color: Color(0xFFBEBEBE),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 28,
                        top: 41,
                        child: Container(
                          width: 48,
                          height: 48,
                          clipBehavior: Clip.antiAlias,
                          decoration:
                              // ignore: deprecated_member_use
                              BoxDecoration(color: Colors.black.withOpacity(0)),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 112.21,
                        top: 30.18,
                        child: SizedBox(
                          width: 118.47,
                          height: 20.91,
                          child: SizedBox(
                            width: 118.47,
                            height: 20.91,
                            child: Text(
                              '소방공무원\n\n이름 :\n\n전화번호 :',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 12,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 19.75,
                top: 319.91,
                child: SizedBox(
                  width: 99.58,
                  height: 30.32,
                  child: SizedBox(
                    width: 99.58,
                    height: 30.32,
                    child: Text(
                      '기타 등등',
                      style: TextStyle(
                        color: Colors.black,
                        fontSize: 12,
                        fontFamily: 'Inter',
                        fontWeight: FontWeight.w400,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20.61,
                top: 171.46,
                child: SizedBox(
                  width: 116.75,
                  height: 64.82,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 20.91,
                        child: SizedBox(
                          width: 116.75,
                          height: 43.91,
                          child: SizedBox(
                            width: 116.75,
                            height: 43.91,
                            child: Text(
                              '아이디\n비밀번호 변경\n이메일 변경',
                              style: TextStyle(
                                color: Color(0xFFBEBEBE),
                                fontSize: 12,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 99.58,
                          height: 30.32,
                          child: SizedBox(
                            width: 99.58,
                            height: 30.32,
                            child: Text(
                              '계정',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 12,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 19.75,
                top: 257.18,
                child: SizedBox(
                  width: 116.75,
                  height: 62.73,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 18.82,
                        child: SizedBox(
                          width: 116.75,
                          height: 43.91,
                          child: SizedBox(
                            width: 116.75,
                            height: 43.91,
                            child: Text(
                              '모드\n알림설정',
                              style: TextStyle(
                                color: Color(0xFFBEBEBE),
                                fontSize: 12,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 99.58,
                          height: 30.32,
                          child: SizedBox(
                            width: 99.58,
                            height: 30.32,
                            child: Text(
                              '설정',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 12,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 399.36,
                child: SizedBox(
                  width: 280,
                  height: 59.59,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 59.59,
                          decoration: BoxDecoration(
                            color: Colors.white,
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x660C0C0D),
                                blurRadius: 32,
                                offset: Offset(0, 16),
                                spreadRadius: -8,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 35,
                        top: 10.45,
                        child: SizedBox(
                          width: 34,
                          height: 44.18,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 22.18,
                                child: SizedBox(
                                  width: 34,
                                  height: 22,
                                  child: ElevatedButton(
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                BigMapGroup()),
                                      );
                                    },
                                    child: Text(
                                      'map',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 219.33,
                        top: 9.41,
                        child: SizedBox(
                          width: 51.85,
                          height: 44.95,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 24.05,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 20.91,
                                  child: SizedBox(
                                    width: 51.85,
                                    height: 20.91,
                                    child: Text(
                                      'profile',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 128.80,
                        top: 10.45,
                        child: Container(
                          width: 51.89,
                          height: 43.91,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0.03,
                                top: 23,
                                child: SizedBox(
                                  width: 51.85,
                                  height: 20.91,
                                  child: ElevatedButton(
                                    onPressed: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                BigChatGroup()),
                                      );
                                    },
                                    child: Text(
                                      'chat',
                                      style: TextStyle(
                                        color: Color(0xFF100F0F),
                                        fontSize: 11,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
