import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Group8(),
        ]),
      ),
    );
  }
}

class Group8 extends StatelessWidget {
  const Group8({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          width: 236.85,
          height: 350,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 53.60,
                child: Container(
                  width: 236.85,
                  height: 296.40,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF261C1C)),
                      borderRadius: BorderRadius.circular(9),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 122,
                child: SizedBox(
                  width: 160,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 7,
                        child: SizedBox(
                          width: 123,
                          height: 23,
                          child: SizedBox(
                            width: 123,
                            height: 23,
                            child: Text(
                              'input text',
                              style: TextStyle(
                                color: Colors.black
                                    // ignore: deprecated_member_use
                                    .withOpacity(0.15000000596046448),
                                fontSize: 14,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 160,
                          height: 30,
                          decoration: BoxDecoration(color: Color(0x4CE0E0E0)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 161,
                child: Container(
                  width: 160,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 7,
                        child: SizedBox(
                          width: 123,
                          height: 23,
                          child: SizedBox(
                            width: 123,
                            height: 23,
                            child: Text(
                              'input text',
                              style: TextStyle(
                                color: Colors.black
                                    // ignore: deprecated_member_use
                                    .withOpacity(0.15000000596046448),
                                fontSize: 14,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 160,
                          height: 30,
                          decoration: BoxDecoration(color: Color(0x4CE0E0E0)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 201,
                child: SizedBox(
                  width: 160,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 7,
                        child: SizedBox(
                          width: 123,
                          height: 23,
                          child: SizedBox(
                            width: 123,
                            height: 23,
                            child: Text(
                              'input text',
                              style: TextStyle(
                                color: Colors.black
                                    // ignore: deprecated_member_use
                                    .withOpacity(0.15000000596046448),
                                fontSize: 14,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 160,
                          height: 30,
                          decoration: BoxDecoration(color: Color(0x4CE0E0E0)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 242,
                child: Container(
                  width: 160,
                  height: 30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 10,
                        top: 7,
                        child: SizedBox(
                          width: 123,
                          height: 23,
                          child: SizedBox(
                            width: 123,
                            height: 23,
                            child: Text(
                              'input text',
                              style: TextStyle(
                                color: Colors.black
                                    // ignore: deprecated_member_use
                                    .withOpacity(0.15000000596046448),
                                fontSize: 14,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 160,
                          height: 30,
                          decoration: BoxDecoration(color: Color(0x4CE0E0E0)),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 45.15,
                top: 0,
                child: Container(
                  width: 146.55,
                  height: 114.30,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/147x114"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 39.59,
                top: 285.36,
                child: Container(
                  width: 158.09,
                  height: 40.91,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 157.67,
                          height: 37.84,
                          decoration: ShapeDecoration(
                            color: Colors.black,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF020000)),
                              borderRadius: BorderRadius.circular(9),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 42.10,
                        top: 5.44,
                        child: SizedBox(
                          width: 115.99,
                          height: 35.47,
                          child: SizedBox(
                            width: 115.99,
                            height: 35.47,
                            child: Text(
                              'register',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 20,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
