import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MainGroup(),
        ]),
      ),
    );
  }
}

class MainGroup extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 340,
          height: 434.11,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 358.23,
                child: Container(
                  width: 340,
                  height: 75.89,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 340,
                          height: 75.89,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF020000)),
                              borderRadius: BorderRadius.circular(9),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 119.65,
                        top: 20.09,
                        child: SizedBox(
                          width: 97.71,
                          height: 30.13,
                          child: SizedBox(
                            width: 97.71,
                            height: 30.13,
                            child: Text(
                              'register',
                              style: TextStyle(
                                color: Colors.black,
                                fontSize: 24,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                height: 1.21,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 340,
                  height: 339.26,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 340,
                          height: 339.26,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFF261C1C)),
                              borderRadius: BorderRadius.circular(9),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 56.83,
                        top: 108.25,
                        child: Container(
                          width: 226.33,
                          height: 180.79,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 136.15,
                                child: Container(
                                  width: 88.74,
                                  height: 44.64,
                                  decoration: ShapeDecoration(
                                    color: Colors.black,
                                    shape: RoundedRectangleBorder(
                                        borderRadius: BorderRadius.circular(9)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24.93,
                                top: 150.66,
                                child: SizedBox(
                                  width: 37.89,
                                  height: 18.97,
                                  child: SizedBox(
                                    width: 37.89,
                                    height: 18.97,
                                    child: Text(
                                      'sign up',
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 10,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 1.21,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 226.33,
                                  height: 44.64,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 226.33,
                                          height: 44.64,
                                          decoration: BoxDecoration(
                                              color: Color(0x4CE0E0E0)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 14.96,
                                        top: 12.28,
                                        child: SizedBox(
                                          width: 173.49,
                                          height: 18.97,
                                          child: SizedBox(
                                            width: 173.49,
                                            height: 18.97,
                                            child: Text(
                                              'input ID',
                                              style: TextStyle(
                                                color: Colors.black.withOpacity(
                                                    0.15000000596046448),
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 1.21,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 72.54,
                                child: Container(
                                  width: 226.33,
                                  height: 44.64,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 226.33,
                                          height: 44.64,
                                          decoration: BoxDecoration(
                                              color: Color(0x4CE0E0E0)),
                                        ),
                                      ),
                                      Positioned(
                                        left: 14.96,
                                        top: 11.16,
                                        child: SizedBox(
                                          width: 173.49,
                                          height: 18.97,
                                          child: SizedBox(
                                            width: 173.49,
                                            height: 18.97,
                                            child: Text(
                                              'input Password',
                                              style: TextStyle(
                                                color: Colors.black.withOpacity(
                                                    0.15000000596046448),
                                                fontSize: 14,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 1.21,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 165.51,
                        top: 244.40,
                        child: Container(
                          width: 117.65,
                          height: 44.64,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 117.65,
                                  height: 44.64,
                                  decoration:
                                      BoxDecoration(color: Color(0x00D9D9D9)),
                                ),
                              ),
                              Positioned(
                                left: 15.95,
                                top: 13.39,
                                child: SizedBox(
                                  width: 86.74,
                                  height: 16.74,
                                  child: SizedBox(
                                    width: 86.74,
                                    height: 16.74,
                                    child: Text(
                                      '𝙛𝙤𝙧𝙜𝙤𝙩 𝙥𝙖𝙨𝙨𝙤𝙬𝙧𝙙?',
                                      style: TextStyle(
                                        color: Colors.black,
                                        fontSize: 10,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        height: 1.21,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
